"""Primera migracion

Revision ID: 1d6f9644a51c
Revises: 
Create Date: 2025-05-05 11:40:49.597982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6f9644a51c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('contrasena', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('chats',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_index(op.f('ix_chats_id_chat'), 'chats', ['id_chat'], unique=False)
    op.create_table('contextos',
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('contexto_numero', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chats.id_chat'], ),
    sa.PrimaryKeyConstraint('id_contexto')
    )
    op.create_index(op.f('ix_contextos_id_contexto'), 'contextos', ['id_contexto'], unique=False)
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_contexto', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chats.id_chat'], ),
    sa.ForeignKeyConstraint(['id_contexto'], ['contextos.id_contexto'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_index(op.f('ix_mensajes_id_mensaje'), 'mensajes', ['id_mensaje'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id_feedback', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensajes.id_mensaje'], ),
    sa.PrimaryKeyConstraint('id_feedback')
    )
    op.create_index(op.f('ix_feedbacks_id_feedback'), 'feedbacks', ['id_feedback'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id_feedback'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_mensajes_id_mensaje'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_contextos_id_contexto'), table_name='contextos')
    op.drop_table('contextos')
    op.drop_index(op.f('ix_chats_id_chat'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
